### ISSUE TITLE
自动重连机制缺陷

### ISSUE THREAD

**Issue by leeyeh** [leancloud/js-realtime-sdk#140]
还原一下事件的经过：

1. ws 断开，SDK 对 ws 的 close 事件没有进行处理
2. guard 程序没有收到心跳，触发重连
3. 在重连的 WebSocket open 前，heartbeats 程序（一旦启动则不会停止）调用 ws.send 发送下一个心跳的时候抛出异常
4. 无人捕获导致程序退出

日志：
```
/root/leancloud/realtime-echo-bot/node_modules/ws/lib/WebSocket.js:214
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/root/leancloud/realtime-echo-bot/node_modules/ws/lib/WebSocket.js:214:16)
    at null._onTimeout (/root/leancloud/realtime-echo-bot/node_modules/leancloud-realtime/src/realtime.js:666:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
error: Forever detected script exited with code: 8
error: Script restart attempt #1

/root/leancloud/realtime-echo-bot/node_modules/leancloud-realtime/src/realtime.js:617
  throw (data);
         ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

**Comment by leeyeh** [comment]
在浏览器端也能复现：http://leancloud-jsbin-dev.herokuapp.com/hociruhupi/embed?js,console
