### ISSUE TITLE
调用RealtimeObject.close()导致ReferenceError

### ISSUE THREAD

**Issue by cnjsstong2** [leancloud/js-realtime-sdk#24]
stack如下：

    ReferenceError: options is not defined
        at Object.engine.closeSession (http://localhost:8888/assets/bower_components/leancloud-realtime/src/lc.realtime.js:485:20)
        at Object.newRealtimeObject.close (http://localhost:8888/assets/bower_components/leancloud-realtime/src/lc.realtime.js:944:24)
        at Object.$get.onLogin (http://localhost:8888/scripts/services/chatService.js:150:42)
        at http://localhost:8888/scripts/controllers/app/front/login.js:14:40
        at processQueue (http://localhost:8888/assets/bower_components/angular/angular.js:13248:27)
        at http://localhost:8888/assets/bower_components/angular/angular.js:13264:27
        at Scope.$get.Scope.$eval (http://localhost:8888/assets/bower_components/angular/angular.js:14466:28)
        at Scope.$get.Scope.$digest (http://localhost:8888/assets/bower_components/angular/angular.js:14282:31)
        at Scope.$get.Scope.$apply (http://localhost:8888/assets/bower_components/angular/angular.js:14571:24)
        at done (http://localhost:8888/assets/bower_components/angular/angular.js:9698:47)

**Comment by wangxiao** [comment]
您好，感谢试用并反馈，已经修复。
https://github.com/leancloud/js-realtime-sdk/pull/25
