### ISSUE TITLE
Uncaught (in promise) Error: createError.js:15

### ISSUE THREAD

**Issue by xgzl87** [leancloud/js-realtime-sdk#411]
Request failed with status code 500
    at a.exports (http://localhost:4400/lib/leancloud-realtime/realtime/realtime.browser.min.js:2:5360)
    at a.exports (http://localhost:4400/lib/leancloud-realtime/realtime/realtime.browser.min.js:2:5504)
    at XMLHttpRequest.n.(anonymous function) (http://localhost:4400/lib/leancloud-realtime/realtime/realtime.browser.min.js:2:9102)

**Comment by xgzl87** [comment]
请问这是什么问题？貌似是请求错误啊

**Comment by leeyeh** [comment]
可以在 network 面板上看一下这个 500 的请求是哪个请求吗

**Comment by xgzl87** [comment]
https://router-g0-push.leancloud.cn/v1/route?appId=********&secure=true&_t=1476324291960

**Comment by xgzl87** [comment]
createError.js:15 Uncaught (in promise) Error: timeout of 20000ms exceeded
    at a.exports (http://localhost:4400/lib/leancloud-realtime/realtime/realtime.browser.min.js:2:5360)
    at XMLHttpRequest.n.ontimeout (http://localhost:4400/lib/leancloud-realtime/realtime/realtime.browser.min.js:2:9198)

**Comment by leeyeh** [comment]
500 的问题我查一下。超时一般是网络原因，请问你用的是国内节点吗，有没有试过换一个网络环境呢？

**Comment by xgzl87** [comment]
哦，无线网可能不稳定

**Comment by sunng87** [comment]
500的问题应该是我们这里的，我尽快调查一下

**Comment by xgzl87** [comment]
appId:aTYSaCsREYpfvHLyYha2cwJ3-********

**Comment by sunng87** [comment]
你好，500 的错误是每次都能重现还是偶尔出现？

**Comment by xgzl87** [comment]
非必先，偶尔出现，我也没找到规律
