### ISSUE TITLE
npm run build的时候出现错误

### ISSUE THREAD

**Issue by Singloo** [leancloud/js-realtime-sdk#598]
输出如下,
已经跑了npm install
node 版本 10.10.0
npm 版本 6.4.1
yarn 版本1.7.0
环境 mac

```
src/index.js → dist/realtime.browser.js...
[!] TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '\u0000commonjs-proxy:/Users/origami/Desktop/js-realtime-sdk/node_modules/babel-runtime/core-js/package.json'
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '\u0000commonjs-proxy:/Users/origami/Desktop/js-realtime-sdk/node_modules/babel-runtime/core-js/package.json'
    at readFile (fs.js:294:3)
    at go$readFile (/Users/origami/Desktop/js-realtime-sdk/node_modules/graceful-fs/graceful-fs.js:73:14)
    at Object.readFile (/Users/origami/Desktop/js-realtime-sdk/node_modules/graceful-fs/graceful-fs.js:70:12)
    at Storage.provide (/Users/origami/Desktop/js-realtime-sdk/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:76:2)
    at CachedInputFileSystem.readFile (/Users/origami/Desktop/js-realtime-sdk/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:234:24)
    at CachedInputFileSystem.<anonymous> (/Users/origami/Desktop/js-realtime-sdk/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:192:9)
    at Storage.provide (/Users/origami/Desktop/js-realtime-sdk/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:76:2)
    at CachedInputFileSystem.readJson (/Users/origami/Desktop/js-realtime-sdk/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:238:24)
    at /Users/origami/Desktop/js-realtime-sdk/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:12:25
    at forEachBail (/Users/origami/Desktop/js-realtime-sdk/node_modules/enhanced-resolve/lib/forEachBail.js:12:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leancloud-realtime@4.2.0 build:realtime: `rollup -c rollup/rollup.config.realtime.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leancloud-realtime@4.2.0 build:realtime script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/origami/.npm/_logs/2018-09-19T07_37_40_199Z-debug.log
error Command failed with exit code 1.
```

**Comment by leeyeh** [comment]
这是一个已知问题，暂时只支持在 Node@8 中 build.

**Comment by Singloo** [comment]
> 这是一个已知问题，暂时只支持在 Node@8 中 build.

好的,多谢

**Comment by leeyeh** [comment]
fixed via https://github.com/leancloud/js-realtime-sdk/commit/ac0df2da6b477ef85340a9fd23701e1d03b90719
