### ISSUE TITLE
小程序 SDK  引入报错

### ISSUE THREAD

**Issue by chenyinlong** [leancloud/js-realtime-sdk#636]
thirdScriptError
Cannot read property '**document**' of undefined
TypeError: Cannot read property 'document' of undefined
    at http://127.0.0.1:57382/appservice/libs/im-weapp.js:104:27
    at http://127.0.0.1:57382/appservice/libs/im-weapp.js:2:65
    at http://127.0.0.1:57382/appservice/libs/im-weapp.js:5:2
    at require (http://127.0.0.1:57382/appservice/__dev__/WAService.js:2:1970551)
    at http://127.0.0.1:57382/appservice/__dev__/WAService.js:2:1970034
    at http://127.0.0.1:57382/appservice/app.js:4:16
    at require (http://127.0.0.1:57382/appservice/__dev__/WAService.js:2:1970551)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:57382/appservice/appservice?t=1591064920174:1136:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:57382/appservice/appservice?t=1591064920174:1148:20)

**Comment by leeyeh** [comment]
fixed via ab3fb953841996f4a406f108c7673bf3fe533bbc

**Comment by leeyeh** [comment]
included in v5.0.0-rc.3
